/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.ryank.studybuddy.editdialogs;

import com.example.ryank.studybuddy.errordialogs.EmptyTextFormErrorDialog;
import com.example.ryank.studybuddy.filesystem.Note;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author ryank
 */
public class EditNoteDialog extends javax.swing.JDialog {

    Note note;
    String title;
    String data;
    boolean isCanceled;

    boolean isFinished;

    /**
     * Creates new form EditNoteDialog
     */
    public EditNoteDialog(java.awt.Frame parent, Note note) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.noteTitleTextField.setText(note.getNoteName());
        this.dataTextArea.setText(note.getNoteData());
        this.note = note;
        isCanceled = false;

        isFinished = false;
        noteTitleTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_TAB) {
                    noteTitleTextField.transferFocus();

                    e.consume();
                }
            }
        });
        dataTextArea.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_TAB) {
                    dataTextArea.transferFocus();

                    e.consume();
                }
            }
        });
        this.noteTitleTextField.grabFocus();
        this.pack();
        this.setVisible(true);
    }

    public EditNoteDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.noteTitleTextField.setText(note.getNoteName());
        this.dataTextArea.setText(note.getNoteData());

        isCanceled = false;

        isFinished = false;
        noteTitleTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_TAB) {
                    noteTitleTextField.transferFocus();

                    e.consume();
                }
            }
        });
        dataTextArea.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_TAB) {
                    dataTextArea.transferFocus();

                    e.consume();
                }
            }
        });
        this.noteTitleTextField.grabFocus();
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        createPlusButton = new javax.swing.JButton();
        noteTitleTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        newDefinitionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancelButton.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createPlusButton.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        createPlusButton.setText("Save Edit");
        createPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlusButtonActionPerformed(evt);
            }
        });

        noteTitleTextField.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        noteTitleTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setText("Title: ");

        newDefinitionLabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        newDefinitionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newDefinitionLabel.setText("Edit Note Definition");

        dataTextArea.setColumns(20);
        dataTextArea.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        dataTextArea.setLineWrap(true);
        dataTextArea.setRows(5);
        dataTextArea.setWrapStyleWord(true);
        dataTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Note", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(dataTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createPlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(noteTitleTextField))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addComponent(newDefinitionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newDefinitionLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createPlusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        isCanceled = true;

        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlusButtonActionPerformed
        if (hasNoText() == false) {
            title = this.noteTitleTextField.getText();
            data = this.dataTextArea.getText();

            isFinished = true;
            isCanceled = false;
            this.setVisible(false);
        } else {
            EmptyTextFormErrorDialog error = new EmptyTextFormErrorDialog(this);
            error.setVisible(true);
        }
    }//GEN-LAST:event_createPlusButtonActionPerformed

    public boolean hasNoText() {
        boolean isEmpty = false;
        if (this.noteTitleTextField.getText().isEmpty() || this.dataTextArea.getText().isEmpty()) {
            isEmpty = true;
        }
        return isEmpty;
    }

    public boolean isCanceled() {
        return isCanceled;
    }

    public boolean isFinished() {
        return isFinished;
    }

    public Note getNewNote() {
        return note;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditNoteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditNoteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditNoteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditNoteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditNoteDialog dialog = new EditNoteDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createPlusButton;
    private javax.swing.JTextArea dataTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel newDefinitionLabel;
    private javax.swing.JTextField noteTitleTextField;
    // End of variables declaration//GEN-END:variables
}
